console.log("tsc sandbox.ts");
console.log("tsc sandbox.ts -w");
// const circ = (diameter: number) => {
//   return diameter * Math.PI;
// };
// console.log(circ(1));
// let letters = ["a", "b", "c"];
// letters.push(1);
// letters.push("d");
// console.log(letters);
// let numbers = [1, 2, 3];
// let numters = [1, "a", 2, "b"];
// let letters: string;
// let numbers: number;
// let isLogggedIn: boolean;
// numbers = 40;
// isLogggedIn = true;
// console.log(numbers, isLogggedIn);
var mixed = [];
mixed.push(10);
mixed.push("greg");
